# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
# Use the alternate form for schema definition instead of using "$schema"="URL" due to stricter
# config parsing added in Yazi 26.5.6. Read more: https://github.com/sxyazi/yazi/issues/3938#issuecomment-4389721843
#:schema https://yazi-rs.github.io/schemas/theme.json

# vscode-light-plus (Light+)
# https://github.com/956MB/vscode.yazi/blob/main/themes/vscode-light-plus/
#
# A theme inspired by Visual Studio Code's Light+ theme.

[colors]
background = "#FFFFFF"
foreground = "#000000"
selection = "#ADD6FF"
cursor = "#000000"
black = "#000000"
red = "#CD3131"
green = "#008000"
yellow = "#949800"
blue = "#0000FF"
magenta = "#AF00DB"
cyan = "#0598BC"
white = "#FFFFFF"
bright_black = "#767676"
bright_red = "#CD3131"
bright_green = "#008000"
bright_yellow = "#949800"
bright_blue = "#0000FF"
bright_magenta = "#AF00DB"
bright_cyan = "#0598BC"
bright_white = "#FFFFFF"

[mgr]
cwd = { fg = "cyan" }

# Find
find_keyword = { fg = "#795E26", bold = true, italic = true, underline = true }
find_position = { fg = "#AF00DB", bg = "#FFFFFF", bold = true, italic = true }

# Marker
marker_copied = { fg = "#008000", bg = "#008000" }
marker_cut = { fg = "#CD3131", bg = "#CD3131" }
marker_marked = { fg = "#0598BC", bg = "#0598BC" }
marker_selected = { fg = "#949800", bg = "#949800" }

# Count
count_copied = { fg = "#FFFFFF", bg = "#008000" }
count_cut = { fg = "#FFFFFF", bg = "#CD3131" }
count_selected = { fg = "#FFFFFF", bg = "#949800" }

# Border
border_symbol = "│"
border_style = { fg = "#D4D4D4" }


[tabs]
active = { fg = "#000000", bg = "#FFFFFF" }
inactive = { fg = "#000000", bg = "#F3F3F3" }


[mode]
normal_main = { fg = "#FFFFFF", bg = "#0000FF", bold = true }
normal_alt = { fg = "#0000FF", bg = "#F3F3F3" }

select_main = { fg = "#FFFFFF", bg = "#FFAF00", bold = true }
select_alt = { fg = "#FFAF00", bg = "#F3F3F3" }

unset_main = { fg = "#FFFFFF", bg = "#CD3131", bold = true }
unset_alt = { fg = "#CD3131", bg = "#F3F3F3" }


[status]
# Permissions
perm_sep = { fg = "#D4D4D4" }
perm_type = { fg = "#008000" }
perm_read = { fg = "#949800" }
perm_write = { fg = "#CD3131" }
perm_exec = { fg = "#0598BC" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#0000FF", bg = "#FFFFFF" }
progress_error = { fg = "#CD3131", bg = "#FFFFFF" }


[pick]
border = { fg = "#0000FF" }
active = { fg = "#AF00DB", bold = true }
inactive = {}


[input]
border = { fg = "#0000FF" }
title = {}
value = {}
selected = { reversed = true }


[cmp]
border = { fg = "#0000FF" }


[tasks]
border = { fg = "#0000FF" }
title = {}
hovered = { underline = true }


[which]
mask = { bg = "#FFFFFF" }
cand = { fg = "#0598BC" }
rest = { fg = "#767676" }
desc = { fg = "#AF00DB" }
separator = "  "
separator_style = { fg = "#767676" }


[help]
on = { fg = "#0598BC" }
run = { fg = "#AF00DB" }
hovered = { bg = "#ADD6FF", bold = true }
footer = { fg = "#000000", bg = "#F3F3F3" }


[spot]
border = { fg = "#0000FF" }
title = { fg = "#0000FF" }
tbl_col = { fg = "#0598BC" }
tbl_cell = { fg = "#AF00DB", bg = "#F3F3F3" }


[notify]
title_info = { fg = "#008000" }
title_warn = { fg = "#949800" }
title_error = { fg = "#CD3131" }


[filetype]
rules = [
    # Images
    { mime = "image/*", fg = "#949800" },
    # Media
    { mime = "{audio,video}/*", fg = "#AF00DB" },
    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#CD3131" },
    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#0598BC" },
    { mime = "application/vnd.openxmlformats-officedocument.*", fg = "#0598BC" },
    # Virtual file system
    { mime = "vfs/{absent,stale}", fg = "#767676" },
    # Fallback
    { url = "*", fg = "#000000" },
    { url = "*/", fg = "#0000FF" },
]


[icon]
dirs = [
    { name = "Desktop", text = "" },
    { name = "Documents", text = "" },
    { name = "Downloads", text = "" },
    { name = "Pictures", text = "" },
    { name = "Music", text = "" },
    { name = "Videos", text = "" },
    { name = ".git", text = "" },
    { name = ".config", text = "" },
]
conds = [
    # Special files
    { if = "orphan", text = "", fg = "#000000" },
    { if = "link", text = "", fg = "#0598BC" },
    { if = "block", text = "", fg = "#949800" },
    { if = "char", text = "", fg = "#949800" },
    { if = "fifo", text = "", fg = "#949800" },
    { if = "sock", text = "", fg = "#949800" },
    { if = "dummy", text = "", fg = "#CD3131" },

    # Fallback
    { if = "dir & hovered", text = "", fg = "#0000FF" },
    { if = "dir", text = "", fg = "#0000FF" },
    { if = "exec", text = "", fg = "#008000" },
    { if = "!dir", text = "", fg = "#000000" },
]
